name: Test Coverage

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt update && sudo apt upgrade && sudo apt install lcov libgrantlee5-dev
    - name: Build
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_COVERAGE=ON -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}
    - name: Collate Coverage
      run: make coverage
      working-directory: ${{ runner.temp }}
    - name: Generate HTML Report
      run: make coverage-html
      working-directory: ${{ runner.temp }}
    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: Test Coverage HTML Report
        path: "${{ runner.temp }}/coverage"
    - name: Submit to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "${{ runner.temp }}/coverage.info"
